# Generated by Django 4.1.7 on 2023-03-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_comment_news_unique author news'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='news',
            name='unique author news',
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
