version: '3'

services:

  db:
    container_name: news_db
    image: postgres:14.5-alpine
    env_file:
      - .env
    networks:
      - news_net
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  web:
    container_name: news_web
    build:
      context: .
      dockerfile: news/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - news_net
    volumes:
      - static:/code/static/
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - web
    networks:
      - news_net
    restart: always

networks:
  news_net:

volumes:
  postgres_data:
  static:
